# Generated by Django 4.1.5 on 2023-02-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='gender',
        ),
    ]
